# Generated by Django 5.2.14 on 2026-05-25 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('preferred_language', models.CharField(blank=True, max_length=100)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('parent_guardian_name', models.CharField(blank=True, max_length=255)),
                ('parent_guardian_email', models.EmailField(blank=True, max_length=254)),
                ('parent_guardian_phone', models.CharField(blank=True, max_length=50)),
                ('academic_status', models.CharField(choices=[('good', 'Good Standing'), ('monitor', 'Monitor'), ('concern', 'Concern'), ('at_risk', 'At Risk')], default='good', max_length=30)),
                ('attendance_concerns', models.TextField(blank=True)),
                ('ossd_credit_progress', models.CharField(choices=[('on_track', 'On Track'), ('behind', 'Behind'), ('complete', 'Complete')], default='on_track', max_length=30)),
                ('graduation_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='pending', max_length=30)),
                ('counselling_status', models.CharField(choices=[('active', 'Active'), ('application_support', 'Application Support'), ('waiting_family', 'Waiting on Family'), ('closed', 'Closed')], default='active', max_length=30)),
                ('homestay_status', models.CharField(choices=[('not_needed', 'Not Needed'), ('searching', 'Searching'), ('confirmed', 'Confirmed'), ('issue', 'Issue')], default='not_needed', max_length=30)),
                ('payment_status', models.CharField(choices=[('clear', 'Clear'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('plan_needed', 'Plan Needed')], default='clear', max_length=30)),
                ('insurance_status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('missing', 'Missing')], default='pending', max_length=20)),
                ('target_country', models.CharField(blank=True, max_length=100)),
                ('target_program', models.CharField(blank=True, max_length=255)),
                ('target_universities', models.TextField(blank=True)),
                ('ielts_english_status', models.CharField(blank=True, max_length=255)),
                ('university_application_status', models.CharField(choices=[('pending', 'Pending'), ('researching', 'Researching'), ('applying', 'Applying'), ('submitted', 'Submitted'), ('offer_received', 'Offer Received'), ('accepted', 'Accepted')], default='pending', max_length=30)),
                ('overall_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20)),
                ('internal_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.student')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('missing', 'Missing')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.student')),
            ],
            options={
                'ordering': ['document_name'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=20)),
                ('method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('meeting', 'Meeting'), ('wechat', 'WeChat'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='email', max_length=20)),
                ('contact_person', models.CharField(max_length=255)),
                ('communicated_at', models.DateTimeField()),
                ('summary', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='cases.student')),
            ],
            options={
                'ordering': ['-communicated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
