# Generated by Django 5.2.14 on 2026-05-25 18:45

import cases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import datetime


def seed_2026_2027_terms(apps, schema_editor):
    AcademicTerm = apps.get_model("cases", "AcademicTerm")
    terms = [
        ("2026-2027", "Semester 1", 1, datetime.date(2026, 9, 1), datetime.date(2026, 11, 6)),
        ("2026-2027", "Semester 2", 2, datetime.date(2026, 11, 10), datetime.date(2027, 1, 28)),
        ("2026-2027", "Semester 3", 3, datetime.date(2027, 2, 2), datetime.date(2027, 4, 19)),
        ("2026-2027", "Semester 4", 4, datetime.date(2027, 4, 21), datetime.date(2027, 6, 28)),
        ("2026-2027", "Summer Semester 1", 5, datetime.date(2027, 7, 5), datetime.date(2027, 7, 29)),
        ("2026-2027", "Summer Semester 2", 6, datetime.date(2027, 8, 3), datetime.date(2027, 8, 27)),
    ]
    for school_year, name, display_order, start_date, end_date in terms:
        AcademicTerm.objects.get_or_create(
            school_year=school_year,
            name=name,
            defaults={
                "display_order": display_order,
                "start_date": start_date,
                "end_date": end_date,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_portal_access_change_requests_and_session_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellingsession',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_year', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['school_year', 'display_order'],
                'unique_together': {('school_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PreparedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.CharField(choices=[('parent', 'Parent/Guardian'), ('agent', 'Agent/Agency')], default='parent', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('summary', models.TextField(blank=True)),
                ('academic_progress', models.TextField(blank=True)),
                ('attendance_update', models.TextField(blank=True)),
                ('counselling_update', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to=cases.models.prepared_report_upload_to)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_reports', to='cases.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='cases.academicterm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=cases.models.request_attachment_upload_to)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.studentrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('attachment', models.FileField(blank=True, upload_to=cases.models.request_response_upload_to)),
                ('mark_complete', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cases.studentrequest')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTermRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_summary', models.TextField(blank=True)),
                ('attendance_summary', models.TextField(blank=True)),
                ('counselling_summary', models.TextField(blank=True)),
                ('agent_notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_records', to='cases.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='cases.academicterm')),
            ],
            options={
                'ordering': ['term__school_year', 'term__display_order'],
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TermCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(blank=True, max_length=50)),
                ('teacher_name', models.CharField(blank=True, max_length=255)),
                ('current_mark', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('term_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='cases.studenttermrecord')),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.RunPython(seed_2026_2027_terms, migrations.RunPython.noop),
    ]
