# Generated by Django 5.2.14 on 2026-05-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_counsellingsession_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedreport',
            name='send_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='preparedreport',
            name='send_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrequestresponse',
            name='send_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentrequestresponse',
            name='send_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
