# Generated by Django 5.2.14 on 2026-05-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_preparedreport_send_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedreport',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preparedreport',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_prepared_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preparedreport',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_student_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='status_before_close',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
