# Generated by Django 5.2.14 on 2026-05-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_counsellingsession_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='case_stage',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('waiting_student', 'Waiting on Student'), ('waiting_parent', 'Waiting on Parent/Agent'), ('application_in_progress', 'Application in Progress'), ('resolved', 'Resolved')], default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
