# Generated by Django 5.2.14 on 2026-05-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_student_case_stage_student_next_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('template_type', models.CharField(choices=[('request', 'Request Response'), ('general', 'General Update')], default='general', max_length=20)),
                ('audience', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent/Guardian'), ('agent', 'Agent'), ('staff', 'Staff'), ('other', 'Other')], default='parent', max_length=20)),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='audience',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent/Guardian'), ('agent', 'Agent'), ('staff', 'Staff'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('request', 'Request Response'), ('report', 'Report Delivery'), ('session', 'Session Communication')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='related_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='cases.preparedreport'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='related_request_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='cases.studentrequestresponse'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='send_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='status',
            field=models.CharField(choices=[('logged', 'Logged'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='logged', max_length=20),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='cases.communicationtemplate'),
        ),
    ]
