# Generated by Django 5.2.14 on 2026-05-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_student_support_team_counsellorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='osslt_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed OSSLT'), ('olc4o', 'Needs OLC4O'), ('olc4o_completed', 'Completed OLC4O'), ('exempt', 'Exempt')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='required_credits',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='student',
            name='volunteer_hours_completed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='volunteer_hours_required',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='studenttermrecord',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studenttermrecord',
            name='planned_course_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
