# Generated by Django 5.2.14 on 2026-05-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_student_date_of_birth_student_osslt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttermrecord',
            name='final_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttermrecord',
            name='midterm_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termcourseenrollment',
            name='final_grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termcourseenrollment',
            name='midterm_grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
