# Generated by Django 5.2.14 on 2026-05-26 21:04

from django.db import migrations, models


def backfill_remaining_progress(apps, schema_editor):
    Student = apps.get_model("cases", "Student")
    for student in Student.objects.all():
        student.credits_remaining_manual = student.required_credits
        student.volunteer_hours_remaining_manual = student.volunteer_hours_required
        student.required_credits = 30
        student.volunteer_hours_required = 40
        student.save(
            update_fields=[
                "credits_remaining_manual",
                "volunteer_hours_remaining_manual",
                "required_credits",
                "volunteer_hours_required",
            ]
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_studenttermrecord_final_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='credits_remaining_manual',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='volunteer_hours_remaining_manual',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_remaining_progress, noop_reverse),
    ]
