from django.urls import path

from .views import (
    AdminToolsView,
    AddPreparedReportView,
    AddStudentRequestView,
    AddStudentCommunicationView,
    AddStudentDocumentView,
    AddStudentNoteView,
    AddStudentTaskView,
    AddStudentTermRecordView,
    AcademicProgressView,
    AddTermCourseView,
    CommunicationCenterView,
    CsvExportDownloadView,
    DatabaseBackupDownloadView,
    DashboardView,
    ParentDashboardView,
    ParentPortalAccessUpdateView,
    ParentUnavailableView,
    PortalDashboardView,
    PortalUnavailableView,
    PortalRequestCreateView,
    PreparedReportUpdateView,
    PreparedReportAttachmentDownloadView,
    ReportsView,
    RequestAttachmentDownloadView,
    RequestResponseAttachmentDownloadView,
    SessionCreateView,
    SessionListView,
    SessionRescheduleRequestView,
    SessionRescheduleSuccessView,
    StudentCreateView,
    StudentDetailView,
    StudentListView,
    StudentPortalAccessUpdateView,
    StudentRequestListView,
    StudentRequestPublicCreateView,
    StudentRequestSuccessView,
    StudentRequestUpdateView,
    StudentUpdateView,
    TaskListView,
    TeamAccessRequestsView,
    UserManagementView,
    UserUpdateView,
)

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("portal/", PortalDashboardView.as_view(), name="portal_dashboard"),
    path("portal/setup-needed/", PortalUnavailableView.as_view(), name="portal_unavailable"),
    path("portal/requests/new/", PortalRequestCreateView.as_view(), name="portal_request_create"),
    path("family/", ParentDashboardView.as_view(), name="parent_dashboard"),
    path("family/setup-needed/", ParentUnavailableView.as_view(), name="parent_unavailable"),
    path("request-support/", StudentRequestPublicCreateView.as_view(), name="student_request_public"),
    path("request-support/thanks/", StudentRequestSuccessView.as_view(), name="student_request_success"),
    path("students/", StudentListView.as_view(), name="student_list"),
    path("students/new/", StudentCreateView.as_view(), name="student_create"),
    path("students/<int:pk>/", StudentDetailView.as_view(), name="student_detail"),
    path("students/<int:pk>/edit/", StudentUpdateView.as_view(), name="student_update"),
    path("students/<int:pk>/portal-access/", StudentPortalAccessUpdateView.as_view(), name="student_portal_access"),
    path("students/<int:pk>/parent-access/", ParentPortalAccessUpdateView.as_view(), name="parent_portal_access"),
    path("students/<int:pk>/notes/add/", AddStudentNoteView.as_view(), name="student_note_add"),
    path("students/<int:pk>/tasks/add/", AddStudentTaskView.as_view(), name="student_task_add"),
    path("students/<int:pk>/requests/add/", AddStudentRequestView.as_view(), name="student_request_add"),
    path("students/<int:pk>/terms/add/", AddStudentTermRecordView.as_view(), name="student_term_add"),
    path("students/<int:pk>/terms/<int:term_record_id>/courses/add/", AddTermCourseView.as_view(), name="student_term_course_add"),
    path("students/<int:pk>/reports/add/", AddPreparedReportView.as_view(), name="student_report_add"),
    path("prepared-reports/<int:pk>/", PreparedReportUpdateView.as_view(), name="prepared_report_update"),
    path("prepared-reports/<int:pk>/attachment/", PreparedReportAttachmentDownloadView.as_view(), name="prepared_report_attachment"),
    path("students/<int:pk>/documents/add/", AddStudentDocumentView.as_view(), name="student_document_add"),
    path(
        "students/<int:pk>/communications/add/",
        AddStudentCommunicationView.as_view(),
        name="student_communication_add",
    ),
    path("requests/", StudentRequestListView.as_view(), name="request_list"),
    path("requests/<int:pk>/edit/", StudentRequestUpdateView.as_view(), name="request_update"),
    path("request-attachments/<int:pk>/", RequestAttachmentDownloadView.as_view(), name="request_attachment_download"),
    path("request-response-attachments/<int:pk>/", RequestResponseAttachmentDownloadView.as_view(), name="request_response_attachment_download"),
    path("sessions/", SessionListView.as_view(), name="session_list"),
    path("sessions/new/", SessionCreateView.as_view(), name="session_create"),
    path("sessions/reschedule/<uuid:token>/", SessionRescheduleRequestView.as_view(), name="session_reschedule"),
    path("sessions/reschedule/success/", SessionRescheduleSuccessView.as_view(), name="session_reschedule_success"),
    path("tasks/", TaskListView.as_view(), name="task_list"),
    path("academics/", AcademicProgressView.as_view(), name="academic_progress"),
    path("team-access/", TeamAccessRequestsView.as_view(), name="team_access_requests"),
    path("communications/", CommunicationCenterView.as_view(), name="communication_center"),
    path("reports/", ReportsView.as_view(), name="reports"),
    path("users/", UserManagementView.as_view(), name="user_management"),
    path("users/<int:pk>/edit/", UserUpdateView.as_view(), name="user_update"),
    path("admin-tools/", AdminToolsView.as_view(), name="admin_tools"),
    path("admin-tools/download-db/", DatabaseBackupDownloadView.as_view(), name="download_db_backup"),
    path("admin-tools/download-csv/", CsvExportDownloadView.as_view(), name="download_csv_export"),
]
